DataDog/datadog-lambda-js

src/trace/context.spec.ts
src/trace/context.ts

*Note: Please remember to review the [contribution guidelines](https://github.com/DataDog/datadog-lambda-layer-js/blob/master/CONTRIBUTING.md)
if you have not yet done so.*
Reads trace headers with case insensitivity.
We were having an issue with some frameworks which would force mixed casing.

Make trace headers case insensitive

---

README.md

Should be `module.exports` instead `exports.exports`

Misspelling in README.md

---

README.md
package.json
src/index.spec.ts
src/index.ts
src/metrics/enhanced-lambda-metrics.ts
src/metrics/enhanced-metrics.ts
src/metrics/index.ts
src/metrics/listener.spec.ts
src/metrics/listener.ts
src/trace/listener.ts
src/utils/arn.spec.ts
src/utils/arn.ts
src/utils/cold-start.spec.ts
src/utils/cold-start.ts
src/utils/handler.spec.ts
src/utils/handler.ts

Increments the `aws.lambda.enhanced.invocations` distribution metric on each function call and increments `aws.lambda.enhanced.errors` when the Lambda handler throws an exception.
Unit tests for the metrics, currently adding the updated layer to functions in the demo account.

Add enhanced lambda metrics

---

README.md
package.json
src/index.spec.ts
src/index.ts
src/metrics/enhanced-metrics.spec.ts
src/metrics/enhanced-metrics.ts
src/utils/process-version.ts

Adds `runtime` and `memorysize` tags to enhanced invocations and errors metrics.
https://trello.com/c/DPjTvXFl/164-add-runtime-and-memorysize-tags-to-layer-enhanced-metrics
Tested and confirmed to work on our demo functions

Add runtime and memorysize tags to enhanced metrics

---

package.json
src/metrics/listener.spec.ts
src/metrics/listener.ts
src/utils/handler.spec.ts
src/utils/handler.ts

Fixes the behavior of the handler wrapper to match the lambda node runtime in the following cases:
- Handlers that never return a value will no longer block until timeout
- Handlers that return a non promise value will have their return values ignored
- Handlers the use the callback, and return a promise, will return with the first to complete
Issue #32 
Added test cases, and manual testing.

Darcy.rayner/fix timeout no return

---

src/index.ts
src/trace/constants.ts
src/trace/context.spec.ts
src/trace/context.ts
src/trace/dd-trace-utils.spec.ts
src/trace/dd-trace-utils.ts
src/trace/listener.spec.ts
src/trace/listener.ts
src/trace/patch-http.spec.ts
src/trace/trace-context-service.ts

Fixes some edge cases with our dd-trace-js integration.
1. Disables datadog-lambda-layer-js patching of http libraries, if the datadog tracer has been initialized
2. By default disables parenting datadog traces to X-Ray traces. There is a new config option, (mergeDatadogXrayTraces), which must be true, before the old behaviour is used. Note, this doesn't disable distributed tracing, which still works the same as before.

Darcy.rayner/support parentless trace

---

src/index.ts
src/utils/index.ts

Noticed we were missing a call to setColdStart() in the wrapper, so enhanced metrics may have been reporting incorrectly for node.

Add missing call to setColdStart

---

.circleci/config.yml
package.json
yarn.lock

Uses a looser version requirement for dd-trace-js. This reduces the chance of a customer using a duplicate copy of the repository, and causing the wrapping code to fail.

Modify dd trace version

---

README.md

Document the experimental feature of using the Datadog tracer (`dd-trace`) in AWS Lambda functions.

Document the experimental feature of using dd-trace in Lambda

---

package.json
src/trace/constants.ts
src/trace/context.spec.ts
src/trace/context.ts

Due to issues where the X-Ray sdk reports an out of date current segment, we need a fallback to use the _X_AMZN_TRACE_ID environment variable to parse trace context instead when merging datadog/X-Ray traces.

Darcy.rayner/use xray env var

---

package.json
src/metrics/build-metric-log.spec.ts
src/metrics/build-metric-log.ts
src/metrics/listener.spec.ts
src/metrics/listener.ts

Fixes the listener to log async metrics with Unix second timestamps rather than the milliseconds that it's currently using. The DD API accepts seconds only so this is causing issues with async metrics when submitted in the log forwarder.
Deployed and tested the layer in staging env and added new unit tests for the metric log generating code.

Fix timestamps for async metrics

---

README.md
package.json
src/index.ts

Enables log context injection by default.
Also updates version number to 2.16.0,(Major version bump, since this is a breaking change).

Enable log injection by default

---

package.json
src/trace/listener.ts

Prevents the layer from unpatching the http lib when the DD tracer is present. When the DD tracer is initialized it handles patching/unpatching on its own.
Unpatching the http lib after function invocations complete was causing the layer to remove the patching that the DD tracer was doing, resulting in correct traces for cold starts but missing HTTP request spans in subsequent executions.
Tested the new version of the layer with our test Lambdas and confirmed that the issue was fixed.

Don't unpatch HTTP lib if the Datadog tracer is initialized

---

src/metrics/enhanced-metrics.spec.ts
src/metrics/enhanced-metrics.ts

When we run local invocation using Serverless framework, the `invokedFunctionArn` context value is undefined.
I really want to test all my lambda in local mode, even if it's very difficult, it's so important to me.
Run a lambda using invoke command locally of the serverless framework with datadog wrapper.

Make getEnhancedMetricTags() works for local invocation

---

.circleci/config.yml
README.md
package.json
scripts/build_layers.sh
scripts/list_layers.sh
scripts/publish_layers.sh
scripts/run_tests.sh
yarn.lock

Upgrades dependencies and drops node 8 support, (this is now fully deprecated by AWS).
Latest version of dd-trace has new aws sdk integration.

Upgrade dependencies, drop node 8 support

---

README.md

This adds documentation around how to add the AWS request ID to logs when using a custom logger, in order to achieve trace-log correlation.

Add documentation and example for adding request ID to logs.

---

README.md
src/index.spec.ts
src/index.ts
src/utils/index.ts
src/utils/log.spec.ts
src/utils/log.ts

Add possibility to provide a custom logger object instead of `console` usage for `logError` and `logDebug`
I use Pino as logger in my lambda, so I wanted to format error and debug log from datadog lambda wrapper as my other logs
Pass a custom logger option and set log level as debug to see logs
~I will add tests and documentation if new feature is accepted~
Tests and documentation added

Be able to provide custom logger to replace console usage

---

package.json
src/trace/listener.ts

Makes the dd-trace root span use a lowercase only function arn. This guarantees the trace will appear on the serverless traces page.

Lowercases function arn on dd-trace spans

---

package.json
src/trace/constants.ts
src/trace/context.spec.ts
src/trace/context.ts
src/trace/patch-console.ts
src/trace/trace-context-service.spec.ts
src/trace/trace-context-service.ts
src/utils/handler.ts
types/aws-xray-sdk-core/index.d.ts
yarn.lock

New version of the xray sdk had significant behaviour changes. Unless initialized, getSegment  and captureFunc would throw an error or log, instead of returning empty. The getSegment call was particularly bad, because it occurred during the patched console.log method, and could generate an infinite loop. This PR:
1. Fixes the console.log issue, by disabling the xray logger temporarily while calling getSegment, catching any errors and also adding a re-entrance check to the patched function. 
1. Removes the captureFunc call used to add datadog metadata to the x-ray trace, and replaces it by calling the daemon directly.

Fix xray-sdk related errors

---

package.json

Serialize-error package wrong version causing the issue refer https://github.com/DataDog/datadog-lambda-layer-js/issues/81
Adds appropriate version on one of the dependecies.
My application build is failing due to this issue caused me to raise this PR
I have just changed the version number to its equivalent NPM version. A DataDog member can test this as required.

Serialize-error package wrong version

---

package.json

A patch release `v2.25.1` for the `datadog-lambda-js` package, to include the dependency fix https://github.com/DataDog/datadog-lambda-layer-js/pull/82.
There is no corresponding layer release.

Patch release v2.25.1

---

src/trace/context.spec.ts
src/trace/context.ts

Socket for send X-Ray sdk payload wasn't being cleaned up correctly, and was causing system to run out of sockets.
Fix for issue #113 .

Cleans up socket after sending payload to x-ray

---

src/utils/handler.spec.ts
src/utils/handler.ts

Fixes issue where lambda wrapper was never completes, due to an undocumented/deprecated API for completing the invocation. [See here](https://stackoverflow.com/questions/54846513/lambda-trigger-callback-vs-context-done)
Because the wrapper was never completing, but the invocation was, trace spans would end up joined together in a mega trace.
I've added unit tests, and also tested this manually to verify the fix.

Fix legacy issue with context.done callbacks

---

src/trace/context.spec.ts
src/trace/context.ts

Fixes an issue with the x-ray socket being closed too early. This causes metadata to not be submitted to x-ray.
Discovered while testing

Fix bug with closing xray socket too early

---

src/trace/patch-http.spec.ts
src/trace/patch-http.ts

Fixes the x-ray only http patching behavior, to account for broken case.
Issue #134
In addition to the new test cases, I've tested this manually in a lambda and verified the request was able to complete correctly.

Fix requests patching edge case

---

package.json

Bumping version from 3.44.0 -> 3.46.0. Skipping 3.45.0 (replica of 3.44.0) since we had one region ahead of others and we needed to match the versions up again.

bump version 3.44.0 -> 3.46.0

---

event_samples/api-gateway-v1.json
package.json
src/trace/trigger.spec.ts
src/trace/trigger.ts

Makes `extractHTTPTags` return immediately after extracting HTTP tags from the trigger event. 
Fixes a bug where API Gateway V1 events were being parsed as V2, resulting in an uncaught exception. Reported by #162 
Added an API Gateway v1 sample request to the unit tests.

Fixes HTTP tag extraction for API Gateway v1 events

---

src/trace/context.ts

Replaces deprecated buffer constructor use with Buffer.from method
Issue #168

Fix use of deprecated Buffer constructor

---

Dockerfile
scripts/publish_layers.sh
scripts/publish_prod.sh

- Move the GovCloud layer publishing steps into the script
- Tie the layer publishing script to a specific version and safe for retry
- Strip out `hdr-histogram-js/build` and `protobufjs/dist` to reduce layer size

Improve layer publishing

---

src/trace/context.spec.ts
src/trace/context.ts
src/utils/request.ts

Fixes error that was caused by a null headers property on event payload, causing listeners to fail to initialize. Also addressed another potentially similar issue around http patching logic.
#174 
Added a unit test to verify issue+fix.

Add null checks when checking for object types

---

src/metrics/listener.spec.ts
src/metrics/listener.ts

Identified issue where extension isn't flushing when 'DD_FLUSH_TO_LOGS' is set to true. This modifies the flow to guarantee the extension is always flushed, and that DD_FLUSH_TO_LOGS is ignored when used with the extension.
Added a unit test, and tested manually.

Fix bug where flushToLogs and the extension would cause timeouts

---

src/trace/patch-console.spec.ts
src/trace/patch-console.ts

Stringifies non-string content that is passed to console.log when trace ID injection is enabled
Received a report of customer logging an object and seeing a log like this written to CW logs:
```
2021-05-19 16:18:03.839 (-04:00)        123-abc-defg-hijk-lmno INFO    [dd.trace_id=1234567 dd.span_id=1234567] [object Object]
```
* Deployed with a sample Lambda and saw the stringified object in the logs
* Added a unit test

Handle non-string logged content with trace ID injection

---

.github/workflows/build.yml
.github/workflows/check-size.yml
scripts/build_layers.sh
scripts/publish_layers.sh
scripts/run_integration_tests.sh
scripts/run_tests.sh
scripts/sign_layers.sh

Bumps node version for v10 runtime, to use node 10.24. (This is the current node 10 runtime AWS is using).
This fixes compatibility issues with some dependencies, that was preventing updates.

Bump node 10 version to 10.24

---

src/metrics/listener.spec.ts

This calls `mock.restore()` after every test in metrics/listener.spec.ts, fixing the problem where some tests wouldn't be run.

Restore mocked filesystem

---

scripts/publish_sandbox.sh
src/metrics/kms-service.spec.ts
src/metrics/kms-service.ts

- import a more specific (lighter) package
- move import logic to decrypt (this way if a lambda does not use KMS, we skip the KMS loading time as well
- unit test kms-service
Performance
Unit tests

Modify KMS import to speed up coldstarts

---

scripts/publish_prod.sh

Updates the regex that checks the desired version in the publish script to make sure you don't prepend it with 'v'. The 'v' confuses Yarn and NPM, and the Git tagging steps assume there will be no 'v'.

Update publish_prod script to fail if the new version is prepended with 'v'

---

scripts/publish_sandbox.sh
src/metrics/kms-service.spec.ts
src/metrics/kms-service.ts

Previously, we assumed that the `DD_KMS_API_KEY` was encrypted using the AWS console. When the API key is encrypted using the console, the console uses the Lambda function's name as an "encryption context". We need to provide this same encryption context in the decrypt call to successfully decrypt the API key. However, if the customer encrypts the API key using the AWS CLI, it will not have this encryption context and the decrypt call will fail.
With this PR, we will first try decrypting the API key without an encryption context, and then attempt to decrypt it with the decryption context.
Encrypting the API key using the AWS console does not work well with our deployment tools, because we expect the customer to provide a single encrypted API key that will work across multiple functions. …

Support decrypting API keys that were encrypted without an encryption context

---

.github/workflows/update-deps.yml

There is a GitHub workflow that runs at 10 AM every day to open a PR updating dependencies. Currently, this workflow will update packages to the latest major version, even if there is a breaking change. For example, it opened [this PR](https://github.com/DataDog/datadog-lambda-js/pull/189) which tried to update `mock-fs` from version 4.x to version 5.x.
Because major versions entail breaking changes, it's not safe to automatically update dependencies to the latest major version. Instead we should respect the dependency ranges specified in the `package.json` file.

Do not automatically open PRs updating packages to latest major version

---

package.json
src/metrics/listener.ts
yarn.lock

Since https://github.com/brightcove/hot-shots/pull/209 has been merged and released here : https://github.com/brightcove/hot-shots/blob/master/CHANGES.md this PR bumps hot-shots to the new released version and make use of the newly introduced parameter `closingFlushInterval` to shutdown StatsD quicker
Performance improvements
Current version :
With the fix :

Remove the forced 50ms wait when closing the StatsD server

---

scripts/publish_prod.sh

Adds a reminder to the end of the publish_prod script reminding the user to update the latest layer version in the docs.

Add reminder to update the latest layer version in the docs

---

package.json
src/trace/trace-context-service.spec.ts
src/trace/trace-context-service.ts
yarn.lock

Removes aws-xray-sdk-core from the layer. This was only used for logs context injection when just using the x-ray library, ( dd-trace-js is disabled). Logs context injection still works without this feature, however the span id will always be set to the root x-ray span.
Reduces bundle size ~4 mb from 15mb to ~11mb. Recent versions of the x-ray library are even larger.

Remove aws-xray-sdk-core

---

src/handler.ts

Switches from the deprecated `blacklist` option in dd-trace-js to the newer `blocklist` when excluding HTTP calls made from dd-lambda-js to the Lambda Extension. The deprecated option is not working properly.
I also updated the blocklist regex from `:8124` to `8124\/lambda`. Both of these regexes work fine for excluding the span, but the new regex will allow other requests made on port 8124 to be traced.
In certain situations, the tracer records a span representing the HTTP call that dd-lambda-js makes to the Lambda Extension at the end of an invocation. It is still unclear to me what exact situations this happens in, but it seems to be caused by differences in the exact order in which modules are imported.
Either way, we want to exclude these spans in all cases. The option we are …

Properly exclude Lambda Extension spans 

---

Dockerfile

This PR strips additional unused files from the node layer, including the protobuf cli tool, .d.ts files and source maps.
Decompressed layer size drops 10mb to 4.8mb.

Strip unused files from the layer

---

src/index.ts

Previously, we incremented the `aws.lambda.enhanced.errors` metric in a window of time between invocations during which the StatsD client is not available. This resulted in the metric not being sent to the Lambda Extension.
I have added integration test coverage in the `datadog-lambda-extension` repository, which will be a separate pull request.

Fix enhanced.errors metric when using Lambda Extension

---

README.md

Document how to apply the wrapper in code
We have encountered a few cases (very rare though) where people have good reasons not being able to redirect the handler, but must apply the wrapper in code. Let's document it.

Document how to apply the wrapper in code

---

src/trace/span-inferrer.spec.ts
src/trace/span-inferrer.ts

This Pull Request fixes the span inferrer for API Gateway V1 events.
Because of this bug, resources are not shown right in DataDog API Gateway service.
I wrote a until test which replicates the bug.
Looks like this problem happens only for API Gateway V1, but I also added an additional test case for API Gateway V2 just to make sure that my changes are not breaking something V2 related.

Span Inferrer: Fix path for API Gateway V1

---

src/metrics/listener.ts

Use logDebug instead of logError if the Agent (extension) is running. The API key is required there, not by this library (unless we are using the forwarder and sending metrics to the backend from this library)
Fixes https://github.com/DataDog/serverless-plugin-datadog/issues/237

fix: Wrap logError in conditional for isAgentRunning, as this is now the agent's responsibility

---

package.json
yarn.lock

Fixes an issue where spans aren't always flushed when a user relies on the AWS SDK to make API calls to managed services

feat: bump dd-trace-js to ^2.9.1

---

scripts/publish_prod.sh

Fixes the auto-generated PR for bumping the version number of the layer after release.

fix: use  instead of  variable which isn't used anymore

---

integration_tests/snapshots/logs/esm_node12.log
integration_tests/snapshots/logs/process-input-traced_node12.log
integration_tests/snapshots/logs/process-input-traced_node14.log
integration_tests/snapshots/logs/process-input-traced_node16.log
integration_tests/snapshots/logs/status-code-500s_node12.log
integration_tests/snapshots/logs/status-code-500s_node14.log
integration_tests/snapshots/logs/status-code-500s_node16.log
integration_tests/snapshots/logs/throw-error-traced_node12.log
scripts/publish_prod.sh
yarn.lock

Removes a local dist directory if it exists, and then copies the cjs handler to be just a regular `handler.js`, which was removed in 6.76 (but phantom-published until 6.82, as yarn doesn't perform clean builds)
closes #305

feat: Clean build and copy handler.js

---

src/trace/trigger.ts

These logs are not technically errors, as they're expected flow in some cases. For example, event bridge triggers do not necessarily need to be ARNs.

Change error logs to debug for trigger type parsing

---

src/index.spec.ts
src/index.ts
src/metrics/extension.ts
src/utils/extension-path.ts

This reverts commit 47c5508488eb67f6a5cdf5c25a73e4971edf02f9.
Revert the commit 47c55084 as it is causing the metrics and traces not sent.
The tests done for the original commit 47c55084 was not correctly setup and caused confusion.

Revert "Lazy load metrics listener  (#320)"

---

src/trace/cold-start-tracer.ts

In theory the tracer will flush when all spans finish. I moved this just before merging this feature, but now think it best to move it back to my original location - after child nodes have been traced.
Just in case, this should prevent us from attempting to flush after every module load span is created.
Units and integration tests passing should suffice here.
No

feat: Move end span after children finish

---

package.json
yarn.lock

Bumps the dependency on DD-trace to 2.27.0 for aws-sdk v3 support
support aws-sdk v3

feat: Bump dd-trace to 2.27.0 for aws-sdk v3 support

---

scripts/publish_layers.sh

Unfortunately this caused an off by one error where we'd apply the wrong `compatible-runtime` flag to published layers.
Fortunately this flag is not actually enforced in Lambda, and is a label only. So this has no runtime implications.
Searching the `publish_layers` codebase, we see this is only used for setting this flag.

fix: drop node12.x from publish script

---

Dockerfile

We've recently expanded the prebuilt profilers from a handful [to several additional prebuilt binaries](https://github.com/DataDog/pprof-nodejs). This has taken a bunch of space, but we only need two prebuilds:
- Linux x86
- Linux arm64
This change strips the rest of the prebuilds out.
Using Cold Start Tracing, I verified that the profiler is still loaded in both x86:
And in arm64:
And I verified profiles are still being created properly:
This saves about 9mb, with the RC on the left, and the latest version 89 on the right:
Performance and binary size reduction
I enabled profiling for both x86 and arm functions and verified they are both working.

feat: Strip prebuilds except linux x86/arm64

---

src/utils/tag-object.spec.ts
src/utils/tag-object.ts

Updates `tagObject.ts` to avoid ignoring booleans.
Since booleans were not considered in this function, they would be avoided and they will not shown in Datadog when opting in for AWS Lambda payload capture.
Updated existing test to use booleans.
n/a

fix: `tagObject` to avoid ignoring booleans

---

src/index.ts
src/trace/context.spec.ts
src/trace/context.ts
src/trace/listener.spec.ts
src/trace/listener.ts
src/trace/trace-context-service.ts

This PR permits a custom trace context extractor to be asynchronous
Fixes #385
I added a new unit test to cover the async path, and repurposed an existing test to cover the synchronous path.
I tested this manually by requesting `datadoghq.com` in an async extractor
```js
module.exports.json = async (payload) => {
const res = await axios.get('https://datadoghq.com');
console.log('GOT RES IN ASYNC HANDLER:', res);
return;
};
```
We can see that the call was awaited and the result returned, even though the extractor returned null, the logged result from [this line](https://github.com/DataDog/datadog-lambda-js/blob/main/src/trace/context.ts#L116) is shown after the request finished:

feat: Support async trace context extraction

---

src/index.ts
src/metrics/enhanced-metrics.ts
src/trace/listener.ts
src/utils/cold-start.spec.ts
src/utils/cold-start.ts
src/utils/index.ts

This PR won't take the first request to a new sandbox as a coldstart if it is greater than 10 seconds old. This is not exhaustive, but indicative of provisioned concurrency.

feat: Handle provisioned concurrency and proactive initialization

---

package.json
yarn.lock

fixes https://github.com/DataDog/dd-trace-js/issues/2893

feat: Bump dd-trace to 3.24 which includes fix for unhandled promise exceptions from lambda handlers

---

src/metrics/kms-service.ts

Hopefully fixes #408
I'm still testing this, want to get it on a PR for integration tests. But apparently our callpath try/catch isn't enough to convince esbuild that this library is provided externally.
I build this project and then tested it locally with `npx esbuild dist/index.js --bundle --minify --platform=node` and did not receive any errors.
For developers finding this in the future, you can test this is error-free by:
1. Pulling this project
2. Running `yarn install`
3. _removing_ `node_modules/@aws-sdk` and `node_modules/aws-sdk` entirely! <- This step is KEY.
4. Running `yarn build`
5. Running `npx esbuild dist/index.js --bundle --minify --platform=node` and confirming you do not receive any build errors.
An esbuild error looks like this:
```
npx esbuild dist/index.js --bundle …
```

feat: Explicitly try/catch require to appease esbuild

---

integration_tests/snapshots/logs/process-input-traced_node14.log
integration_tests/snapshots/logs/process-input-traced_node16.log
integration_tests/snapshots/logs/process-input-traced_node18.log
integration_tests/snapshots/logs/status-code-500s_node14.log
integration_tests/snapshots/logs/status-code-500s_node16.log
integration_tests/snapshots/logs/status-code-500s_node18.log
package.json
yarn.lock

fixes #404
Fixes an issue where aws-sdk can not be instrumented when directly importing an indvidual client or clients.

feat: bump dd-trace-js

---

integration_tests/snapshots/logs/process-input-traced_node14.log
integration_tests/snapshots/logs/process-input-traced_node16.log
integration_tests/snapshots/logs/process-input-traced_node18.log
integration_tests/snapshots/logs/status-code-500s_node14.log
integration_tests/snapshots/logs/status-code-500s_node16.log
integration_tests/snapshots/logs/status-code-500s_node18.log
package.json
yarn.lock

Bumps to the latest minor of ddtracejs, staying on the 3.x line as it supports all current versions of node in AWS.

feat: Bump ddtrace to 3.38.1

---

scripts/publish_layers.sh
scripts/publish_sandbox.sh

1. Revives some old code which spins off child processes (with `&`) and tracks the pids up to a batch size to make backfilling layers faster
2. *removes the backfill confirmation logic* and instead warns:
3. Removes the region arg, we already ask/confirm so if they don't pass it, we don't need to choose it:
I've never said "no" to a backfill, and I can't think of a condition where we would say no unless we inadvertently used a large number for the target version (eg 999 instead of 99). This script could simply be killed and started again with the lower number, as lambda will only let us increment versions upwards anyways.

feat: use multiple processes to publish layers

---

integration_tests/snapshots/logs/process-input-traced_node14.log
integration_tests/snapshots/logs/process-input-traced_node16.log
integration_tests/snapshots/logs/process-input-traced_node18.log
integration_tests/snapshots/logs/process-input-traced_node20.log
integration_tests/snapshots/logs/status-code-500s_node14.log
integration_tests/snapshots/logs/status-code-500s_node16.log
integration_tests/snapshots/logs/status-code-500s_node18.log
integration_tests/snapshots/logs/status-code-500s_node20.log
package.json
scripts/run_integration_tests.sh
src/runtime/require-tracer.spec.ts
src/runtime/require-tracer.ts
yarn.lock

Bumps `dd-trace` to `v3.41.0`.
Support W3C 128bit trace IDs.
Updated integration tests.
This PR also adds the `dc-polyfill` dependency required to use with `dd-trace`.

feat: bump ddtrace to 3.41.0

---

src/trace/span-context-wrapper.spec.ts
src/trace/span-context-wrapper.ts

This PR ensures that the traceId and spanId are boxed as a String object when creating the dd-trace/span-context type (so that later it won't error out [when calling toArray()](https://github.com/DataDog/dd-trace-js/blob/9c71b3060081a77639bab4c6b2a26c952f4a114f/packages/dd-trace/src/encode/0.4.js#L168))
We have a customer issue linked here. 
The error stacktrace is 
```
2023-12-07T13:57:10.020Z	c241f8c3-8001-4a5d-a333-6ae15155d2a2	DEBUG	{
"status": "debug",
"message": "id.toArray is not a function",
"name": "TypeError",
"stack": "TypeError: id.toArray is not a function\n    at AgentEncoder._encodeId (/var/task/node_modules/dd-trace/packages/dd-trace/src/encode/0.4.js:168:13)\n    at AgentEncoder._encode (/var/task/node_modules/dd-trace/packages/dd-trace/src/encode/0.4.js:96:12)\n    at …
```

[SLES-1463] [bugfix] ddtrace spancontext traceid need to be object

---

src/index.ts
src/metrics/listener.spec.ts
src/metrics/listener.ts

Removes the call to `/flush`, as the telemetry-api tells us this information now
Fixes #452 
We'd like to remove this entirely but it's required for people using the extension in a local testing mode. We don't intend to further support local testing in this library at this time.

feat: Skip the flush() call unless the DD_LOCAL_TEST env var is set

---

src/trace/span-context-wrapper.spec.ts
src/trace/span-context-wrapper.ts

Fix id.toArray() issue

---

src/utils/request.ts

Fully fixes the FD leak by discarding the `response` stream using `resume()`
We already discard the result of any GET or POST here, and always have (which we know from the types returning only a status code), so `resume()` is fine here.
I was under the impression that since we did not provide `response.on('data', cb)` that this clause wouldn't apply and the response stream would be ignored:
>If no [`'response'`](https://nodejs.org/api/http.html#event-response) handler is added, then the response will be entirely discarded. However, if a [`'response'`](https://nodejs.org/api/http.html#event-response) event handler is added, then the data from the response object **must** be consumed, either by calling `response.read()` whenever there is a `'readable'` event, or by adding …

feat: Fix FD leak in request

---

src/utils/tag-object.spec.ts
src/utils/tag-object.ts

[SVLS-3853] handle the null case first before handling max depth

---

integration_tests/serverless.yml
src/utils/tag-object.spec.ts
src/utils/tag-object.ts

[SVLS-3853] handle empty function case in tag-object

---

src/trace/span-context-wrapper.spec.ts
src/trace/span-context-wrapper.ts

Fixes a bug in which reading sampling priority will cause an error, because it was undefined. Previously, before adding W3C, we'd just set always `AUTO_KEEP`, but now we decided on getting whatever the trace context had. 
Now, if not available, we'll go back to using `AUTO_KEEP`, while respecting whichever was there before if set.
#482 
Added unit tests.
Introduced in: https://github.com/DataDog/datadog-lambda-js/commit/f05c6003a4f7bab82e46e741ac8d0c98d89efe5b#diff-8367049249917f97a7d4b0d7aa3355ac631ce80bd38d35f0f04c9288c603b76a

fix: reading sampling priority will error when not available

---

ci/datasources/regions.yaml

Fixes #495
eu-north-1 was omitted from the list of regions for ci-based deploys, so we're a couple releases behind here.

feat: add eu-north-1

---

Dockerfile
ci/input_files/build.yaml.tpl
scripts/build_layers.sh
scripts/run_tests.sh

Build and integration tests occasionally fail with rate limit errors, because I used the wrong URL:

feat: Use mirror to fix rate limit issue

---

.github/workflows/build.yml
.github/workflows/update-snapshots.yml

`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

ci: Use GITHUB_OUTPUT envvar instead of set-output command

---

ci/input_files/build.yaml.tpl
ci/publish_npm.sh

Prevents #503.
The new ci-based release logic never used `set -e`, and thus when `tsc` wasn't found, it published the typescript code (but not js) to npm:
This PR should fix that, and installs tsc correctly.

fix: release script should exit on error.

---

Dockerfile

node-gyp-build replaces? this in dd-trace-js, so we don't have this dependency anymore and the build is successful without it.

feat: Remove node-gyp from build container

---

package.json
src/trace/context/extractors/sqs.spec.ts
src/trace/context/extractors/sqs.ts
src/trace/xray-service.spec.ts
src/trace/xray-service.ts

In the case where 
Java lambda ==> SQS ==> NodeJS lambda
the tracecontext is injected into the `Records[i].attributes.AWSTraceHeader`.
This PR refactors around XRayService and SQSEventTraceExtractor to extract that context out.
Result:

Extract trace context from AWSTraceHeader in SQS java upstream case

---

src/metrics/extension.spec.ts
src/metrics/extension.ts
src/metrics/listener.spec.ts

Checking the file presence is enough, start order is enforced by the lambda runtime.

feat: Remove extension hello check as it's redundant

---

src/metrics/extension.spec.ts
src/metrics/extension.ts
src/metrics/listener.spec.ts
src/metrics/listener.ts

Renames `agent` to `extension` in `extension.ts` and some other files.
Just because.
N/A

chore: rename Agent to Extension

---

integration_tests/send-metrics.js
integration_tests/snapshots/logs/async-metrics_node16.log
integration_tests/snapshots/logs/async-metrics_node18.log
integration_tests/snapshots/logs/async-metrics_node20.log
src/index.spec.ts
src/index.ts
src/metrics/index.ts
src/metrics/queue.spec.ts
src/metrics/queue.ts
src/utils/index.ts
src/utils/log.spec.ts
src/utils/log.ts

Allows customer to use the API `sendDistributionMetric` and `sendDistributionMetricWithDate` outside of the handler.
#515 
- Added unit tests
- Added integration test
- Tested manually
[SVLS-4633](https://datadoghq.atlassian.net/browse/SVLS-4633)
[SVLS-4633]: https://datadoghq.atlassian.net/browse/SVLS-4633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: support sending metrics before handler initialization

---

src/metrics/listener.spec.ts
src/metrics/listener.ts

Allows `sendDistributionMetricWithDate` to submit a metric with a timestamp when the Extension is running. Neither hot-shots nor Dogstatsd supports historical distribution metrics (more on the latter [here](https://github.com/Datadog/architecture/blob/master/rfcs/dogstatsd-no-aggregation-pipeline/rfc.md) and [here](https://datadoghq.atlassian.net/browse/FRMETS-1843)).
The ability to send metrics with timestamps already existed but did not work when using the Extension.
* [SVLS-4422](https://datadoghq.atlassian.net/browse/SVLS-4422)
* Related to: 
* **TODO**: https://github.com/DataDog/datadog-lambda-python/issues/398 
* https://github.com/DataDog/datadog-lambda-js/issues/58 
Unit test + manual tests. Example of one invocation using the following:
```js
const MS_PER_MINUTE = 60000;
const …
```

[SVLS-4422] Support metrics with timestamps when the Extension is running

---

event_samples/api-gateway-v1-parametrized.json
event_samples/api-gateway-v2-parametrized.json
src/trace/span-inferrer.spec.ts
src/trace/span-inferrer.ts

Set the resource name to the parameterized route key when using api gateway v2.
A metric is created from each span made by the tracers. The metric name comes from the operation name. The resource name gets added as a tag. Therefore unbound values for resource name can cause a large increase in the number of metrics on an account.
To test this, I created two apps and pulled the event payloads for each to use in the unit tests.
```yaml
functions:
v1:
handler: handler.handler
events:
- http:
method: get
path: /user/{id}
v2:
handler: handler.handler
events:
- httpApi:
method: get
path: /user/{id}
```
This feature already worked for api gatewawy v1.

Favor parameterized routes for resource name.

---

package.json
yarn.lock

Pins `shimmer` to `1.2.1`
[VULN-6247](https://datadoghq.atlassian.net/browse/VULN-6247)
GitHub Checks
[VULN-6247]: https://datadoghq.atlassian.net/browse/VULN-6247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: pin `shimmer` to `1.2.1`

---

src/trace/context/extractors/sns-sqs.spec.ts
src/trace/context/extractors/sns-sqs.ts
src/trace/context/extractors/sns.spec.ts
src/trace/context/extractors/sns.ts
src/trace/context/extractors/sqs.spec.ts
src/trace/context/extractors/sqs.ts
src/trace/xray-service.spec.ts
src/trace/xray-service.ts

Extract trace context in SNS and SQS cases where the upstream service is instrumented by dd-trace-java
In short, 
1. For `Java => SNS => Lambda`, the env: _X_AMZN_TRACE_ID has the dd trace id but not the correct parent id. We will still use it here.
2. For `Java => SQS => Lambda` or `Java => SNS => SQS => Lambda` case, AWS propagate the trace context in the json payload attributes. 
Longer version:
- Unittests added
- Integration tests added https://github.com/DataDog/dd-trace-x-lambda-examples/blob/main/lib/wip-cases/sns-java-checks-nested-stack.ts
- Manually tested (You can see the parenting issue causing a white space between spans)
Single Message Publish
Batch Publish

[SVLS-4780] upstream Java sns and sqs refactor

---

scripts/publish_prod.sh

This PR removes the `ddsaml2aws` login from the publish prod script.
Govcloud access has been fully migrated to use SSO.

Remove ddsaml2aws login from release script

---

src/utils/tag-object.spec.ts
src/utils/tag-object.ts

When the response object contains a circular reference, `JSON.stringify` will throw an error. This should be caught and ignored.
Fixes https://github.com/DataDog/datadog-lambda-js/issues/541

Capture and handle errors during stringify.

---

package.json
scripts/run_integration_tests.sh
src/trace/context/extractor.spec.ts
src/trace/context/extractors/step-function.spec.ts
src/trace/step-function-service.spec.ts
src/trace/step-function-service.ts
yarn.lock

- using the most significant 128 bits of sha256 (instead of current md5) to hash trace_id and the first 64 for span_id.
- the 1st and 65th bit should be `0`.
- manually take:
- the first 64 bits from the sha256 hash for `_dd.p.tid` tag
- the 2nd 64 bits from the sha256 hash for `traceId`
- if it were for spanId, use sha256 hash for `parentId` (which is step function task's spanId)
- `ts-md5` package is remove.
- @node/type in DevDependencies needs to be upgraded by running `yarn add @types/node -D` as suggested in this the issue https://github.com/microsoft/TypeScript/issues/51567
- note that for the root span it has span_id in number but trace_id in hex
- [relevant PR for 64 bits using md5](https://github.com/DataDog/datadog-lambda-js/pull/331)
```
{
"trace": {
"root_id": …
```

breaking: Use sha256 to hash lambda traceId that are triggered by Step Functions  and set _dd.p.tid

---

src/runtime/module_importer.js
src/utils/dd_tags.spec.ts
src/utils/dd_tags.ts
src/utils/index.ts

Prevents `DD_TAGS` from being overwritten.
Customer escalation

ensure tracer initialization does not override DD_TAGS

---

src/trace/context/extractor.spec.ts
src/trace/context/extractors/step-function.spec.ts
src/trace/step-function-service.spec.ts
src/trace/step-function-service.ts

Step Function events that are from Legacy Lambda enter the layer wrapped in a `Payload: {}`. Here's an example
```
{'Payload': {'Execution': {'Id': 'arn:aws:states:sa-east-1:425362996713:execution:abhinav-legacy-lam-sf:ca7383bc-e370-4a85-a266-a4686bd7d00f', 'Input': {}, 'StartTime': '2024-08-08T18:55:03.805Z', 'Name': 'ca7383bc-e370-4a85-a266-a4686bd7d00f', 'RoleArn': 'arn:aws:iam::425362996713:role/service-role/StepFunctions-abhinav-test-1-role-4u48d0717', 'RedriveCount': 0}, 'StateMachine': {'Id': 'arn:aws:states:sa-east-1:425362996713:stateMachine:abhinav-legacy-lam-sf', 'Name': 'abhinav-legacy-lam-sf'}, 'State': {'Name': 'Lambda Invoke', 'EnteredTime': '2024-08-08T18:55:03.847Z', 'RetryCount': 0}}}
```
This change will check if events fall into this case and parse them accordingly so …

Step Functions Legacy Lambda Span Linking

---

Dockerfile

Removes some browser files we don't need in Lambda, also some sourcemaps

feat: Remove browser-specific files

---

Dockerfile

Remove libdatadog from dd-trace.
It increases the size of the package and is not a feature we want to ship in Serverless for now.

remove libdatadog from dd-trace

---

src/metrics/listener.ts

This PR adds buffering to our StatsD client to support higher volumes of custom metrics. This is accomplished by setting the `maxBufferSize` to a number (by default it is set to 0 for no buffering at all).
When there is no buffer, we make a request (over localhost) to the Extension every time `sendDistributionMetric()` is called. When there is a buffer, we keep adding custom metrics to the buffer until we flush the buffer, which happens when (1) the buffer size is reached, (2) every `bufferFlushInterval` milliseconds occurs (currently defaults to 1000ms), or (3) the Lambda function is done executing.
The value of `maxBufferSize` is the size of the payload string, not the number of metrics in the buffer. See https://github.com/brightcove/hot-shots for more documentation.
See the section at …

Enable metric buffering

---

event_samples/states.json
src/trace/context/extractor.spec.ts
src/trace/step-function-service.spec.ts
src/trace/step-function-service.ts
src/trace/trigger.spec.ts
src/trace/trigger.ts
src/utils/event-type-guards.ts

Allows us to do multi-level trace merging between Step Functions and Node Lambda functions
Added logic to extract trace context from `_datadog` for Step Functions cases where...
1. Root of the overall execution is a Lambda. This means we have the `x-datadog-trace-id` and `x-datadog-tags` but we need to compute the parentID using parent SFN context object
2. Root of the overall execution is another Step Function. This means we need to compute both traceID and parentID from `RootExecutionId` and the parent SFN context object
3. Legacy case where there's no `_datadog` and we instead figure out traceID and parentID from the parent SFN context object
1. `Lambda1 --> SFN --> Lambda2` [trace](https://dd.datad0g.com/apm/trace/673b667c000000001440b57672af3118?graphType=flamegraph&shouldShowLegend=t …

Step Functions Trace Merging Support

---

package.json
src/utils/span-pointers.spec.ts
src/utils/span-pointers.ts
yarn.lock

Upgrades `dd-trace` to `v4.53.0`
Updates span pointer imports, since we changed the location of the utils in the v4.53.0 release.
Load in new span pointer features: https://github.com/DataDog/dd-trace-js/pull/4912

chore: upgrade `dd-trace` to `v4.53.0`

---

src/trace/context/extractors/step-function.spec.ts
src/trace/step-function-service.spec.ts
src/trace/step-function-service.ts

Account for missing redrive count in Step Functions trace merging. While we expect the context object to always have `Execution.RedriveCount`, some customers context objects don't have this value.

Redrive Trace Merging Fix

---

src/index.ts
src/trace/listener.spec.ts
src/trace/listener.ts
src/utils/span-pointers.ts

1. Adds an env var `DD_TRACE_AWS_ADD_SPAN_POINTERS` to toggle span pointers
2. Put span pointers on inferred (root) span instead of the lambda (child) span, as discussed in Slack.
3. Wrap `span.addSpanPointers` with try/catch, since `span` is of type any.
Note that moving the location of the span pointer has no actual effect on the functionality and requires no changes on the UI side. As long as a span is found with a matching hash, span pointers work. Since the spans are on the same trace, this has no noticeable change for our users. This change just aligns span pointers with bottlecap (universally instrumented) runtimes.
Manual testing. The span links are now on the root (inferred) span.

Move span pointer to inferred span; add env var to toggle span pointers

---

.gitlab/scripts/get_secrets.sh

Migrates secret storage from AWS SSM to Vault.
Secrets: https://vault.us1.ddbuild.io/ui/vault/secrets/kv/kv/k8s%2Fgitlab-runner%2Fdatadog-lambda-js%2Fsecrets/details?version=2
Proper secret storage in Gitlab: https://datadoghq.atlassian.net/wiki/spaces/SECENG/pages/3826647944/Secure+Storage+and+Handling+of+Secrets#In-GitLab
- Integration tests passed, so the `vault kv get -field=dd-api-key` works
- I published to a random region in sandbox successfully, so the `vault kv get -field=$EXTERNAL_ID_NAME` works. https://gitlab.ddbuild.io/DataDog/datadog-lambda-js/-/jobs/807550522
Related PR: https://github.com/DataDog/vault-config/pull/7119

[gitlab] Get secrets from vault

---

.gitlab/input_files/build.yaml.tpl
.gitlab/scripts/publish_layers.sh
scripts/publish_govcloud_layers.sh

Creates a job in Gitlab to bundle all the layer zips into a single zip so we no longer have to manually download each layer manually.
This PR also creates `scripts/publish_govcloud_layers.sh` to publish layers to either Govcloud or Govcloud staging.
Copying logic from https://github.com/DataDog/datadog-lambda-extension/pull/556/
Easier testing of layers for FIPs compliance + easier time publishing to Govcloud
Manually.
Layer bundle passed:
and produces the correct artifact as expected:
and running the script (on staging) works as expected:
```sh
ENVIRONMENT=us1-staging-fed REGIONS=us-gov-west-1 ./scripts/publish_govcloud_layers.sh <path from dragging bundle.zip file>
```
Basically all the same logic as the datadog-lambda-extension implementation. But there is no 'flavors' since each layer …

Create bundle and publish to govcloud script

---

src/metrics/listener.spec.ts
src/metrics/listener.ts

When creating the `SecretsManager` client, set `useFipsEndpoint` to true if in a govcloud region.
Will get to KMS key storage in a following PR.
Making our products FIPs compliant.
Manually. Secrets manager works in both Govcloud and commercial regions.
Added a simple unit test

Use FIPs endpoint for SecretManager when in Govcloud region

---

src/metrics/kms-service.spec.ts
src/metrics/kms-service.ts

When creating the `kmsClient`, set `useFipsEndpoint` to true if in a govcloud region.
Making our products FIPs compliant.
Manually. Works in both Govcloud and commercial regions.
Related PR: https://github.com/DataDog/datadog-lambda-js/pull/634

Use FIPs endpoint for KMS when in Govcloud region

---

integration_tests/snapshots/logs/process-input-traced_node18.log
integration_tests/snapshots/logs/process-input-traced_node20.log
integration_tests/snapshots/logs/process-input-traced_node22.log
integration_tests/snapshots/logs/status-code-500s_node18.log
integration_tests/snapshots/logs/status-code-500s_node20.log
integration_tests/snapshots/logs/status-code-500s_node22.log
package.json
yarn.lock

Upgrades tracer to `v5.41.1`
Incident on past release
Checks

chore: upgrade tracer to `v5.41.1`

---

src/metrics/listener.spec.ts
src/metrics/listener.ts

Users could be storing their secret in SecretsManager in a different region than the currently running Lambda. This parses the arn for the correct region.
Before this change, users would get error: `Secrets Manager can't find the specified secret.`
Backports https://github.com/DataDog/datadog-lambda-extension/pull/604
Unit tests
- Tested manually with secret in same region, and it works
- Tested manually with secret in different region, and it works

Use correct SecretsManager region

---

package.json
yarn.lock

Upgrades the tracer to `v5.42.0`
So we can get the performance gains from @rochdev 
Checks

chore: upgrade tracer to `v5.42.0`

---

src/trace/trigger.spec.ts
src/trace/trigger.ts

Handles case where the status code is a string instead of a number.
We extract this status code in `extractHTTPStatusCodeTag()` 
https://github.com/DataDog/datadog-lambda-js/issues/641
Manual+unit

Extract status code when returned as string

---

src/metrics/listener.ts
src/metrics/processor.ts

- add warning in case a failed send will drop metrics received during the try
- do not create one promise per metric. This would let the process to wait for only one promise and avoid missing metrics https://github.com/DataDog/datadog-lambda-js/issues/638

Sles 2151 fix race condition flush

---

event_samples/application-load-balancer-multivalue-headers.json
src/trace/context/extractor.ts
src/trace/context/extractors/http.spec.ts
src/trace/context/extractors/http.ts

Support trace extraction when we receive `multiValueHeaders` instead of `headers`. This can happen if multi value headers are turned on in ALB.
The event payload structure for multiValueHeaders is defined here: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/lambda-functions.html
https://github.com/DataDog/datadog-lambda-js/issues/603
https://datadoghq.atlassian.net/browse/SVLS-6725
Manually, unit tests

Extract trace context from ALB multiValueHeaders

---

LICENSE-3rdparty.csv
package.json
src/index.spec.ts
src/metrics/dogstatsd.spec.ts
src/metrics/dogstatsd.ts
src/metrics/listener.spec.ts
src/metrics/listener.ts
src/metrics/metric-log.spec.ts
src/metrics/metric-log.ts
yarn.lock

- Removes `hot-shots`
- Implements dogstatsd ourselves
- Updates dogstatsd implementation to support timestamps
- Therefore, if the user has extension enabled and sends a metric with a timestamp, we can now use dogstatsd instead of directly using the API
- This PR also implements a working `flush`. The previous implementation just closed the UDP socket on "flush" which actually just drops any unsent UDP packets, leading to lost metrics.
- Just use one socket, no need to keep opening/closing sockets on every invocation
- `hot-shots` did not support metrics with timestamps, so originally we just sent metrics directly using the Datadog API
- However, the DD API is not FIPs compliant. This seemed like the easiest solution
- dogstatsd is a very simple protocol so might as well do it ourselves. …

Implement dogstatsd, add timestamp support, fix flushing

---

src/metrics/listener.ts

- In https://github.com/DataDog/datadog-lambda-js/pull/616, we upgraded aws-sdk to v3 for SecretsManager
- In Lambda, v3 of SecretsManager can cause a SignatureDoesNotMatch error in Lambda: https://github.com/aws/aws-sdk-js-v3/issues/5192#issuecomment-2073243617
- Due to proactive initialization, a busy Lambda might have a container initialize more than 5 minutes before the first invocation
- Originally, we were creating the SecretsManager client during initialization. Since `getAPIKey` is an async function, it may get paused after importing SecretsManager and may not continue with the `getSecretValue` call until the first invocation
- If there's a >5 min gap, we get errors
- To resolve this, we can just get the API key during the first invocation
```typescript
if (config.apiKeySecretARN …
```

Fix SignatureDoesNotMatch error when SecretsManager enabled

---

.github/workflows/update-deps.yml

Makes the upgrade workflow use GitHub Apps to get temporary tokens instead of using a long-lived SSH key.
This workflow is broken, probably because the SSH key no longer works. Instead of creating a new SSH key, we use a GitHub App, which generates short-lived tokens and is more secure than SSH key.
Will test the workflow after this PR is merged to `main` because I can't manually trigger it right now.
Jira: https://datadoghq.atlassian.net/browse/SVLS-6929

chore: Use GitHub App for update-deps workflow

---

package.json
src/utils/span-pointers.ts
yarn.lock

- Bumps dd-trace-js
- @types/jest v26 is incompatible with jest v27, so it needed to be upgraded for `npm install` to work.
- the `extractPrimaryKeys` function defined in the tracer was updated in https://github.com/DataDog/dd-trace-js/pull/5790 to take an array instead of set, so we needed to update the call here. Span pointers should still work fine after this change, but I will run e2e tests before the next release to make sure

Bump dd-trace to 5.56.0

---

src/index.spec.ts
src/trace/listener.spec.ts
src/trace/listener.ts
src/trace/trace-context-service.spec.ts
src/trace/trace-context-service.ts

The customer is experiencing a case where multiple lambda invocations are put into one trace even though they have different tracecontext in their payload. This indicates that the `rootTraceContext` was reused/cached unintentionally. 
https://datadoghq.atlassian.net/browse/APMS-17080

fix: reset tracecontext to avoid unintentional caching
