.circleci/config.yml, package.json
Adds code coverage uploading to build process
=> Darcy.rayner/codecov reports

README.md
*Note: Please remember to review the [contribution guidelines](https://github.com/DataDog/datadog-lambda-layer-js/blob/master/CONTRIBUTING.md)
if you have not yet done so.*
Adds some badges to the readme
=> Add package badges

.circleci/config.yml, README.md
Just realized we weren't documenting DD_FLUSH_TO_LOG either.
A brief description of the change being made with this pull request.
=> Add missing env var to docs

package.json, src/index.spec.ts, src/index.ts, src/trace/datadog-tracer.ts, src/trace/index.ts, src/trace/listener.ts, src/utils/handler.spec.ts, src/utils/handler.ts, yarn.lock
Adds experimental integration with the dd-trace library, by exporting trace metadata to logs.
=> Experimental Integration with dd-trace

scripts/list_layers.sh, scripts/publish_layers.sh
Adds the new eu-north-1 region to our build scripts.
=> Darcy.rayner/add eu north 1

.circleci/config.yml, package.json, scripts/build_layers.sh, scripts/list_layers.sh, scripts/publish_layers.sh, scripts/run_tests.sh, yarn.lock
Updates dependencies to latest versions, and adds node 12 lambda layer for new runtime.
=> Add node 12 support

src/metrics/listener.ts
Debug log was being skipped, through a bad nested if statement
=> Fix broken API key debug log

scripts/publish_layers.sh
Speeds up publishing of layers by forking the process
=> Add parallel publishing to script

.circleci/config.yml
Bump up circleci memory.
Tests unable to run due to the lack of memory.
=> Bump memory to 8G

README.md
*Note: Please remember to review the [contribution guidelines](https://github.com/DataDog/datadog-lambda-layer-js/blob/master/CONTRIBUTING.md)
if you have not yet done so.*
A brief description of the change being made with this pull request.
=> Bump trace forwarder version in readme

scripts/list_layers.sh, scripts/publish_layers.sh
Adds ap-east-1 region
Need to support new region in aws
=> Add ap-east-1 region to build scripts

README.md, scripts/publish_prod.sh, src/trace/listener.spec.ts, src/trace/listener.ts, src/trace/trace-context-service.ts
* Downgrades an error from reading X-Ray to a debug log
* Correctly sets the root span type to serverless
* Disable testing in publish script, (CI is enough, and it breaks locally for some reason).
* Updates readme with information on setting up latest beta
=> Downgrade xray error

package.json, src/utils/handler.ts, yarn.lock
Improves the error message formatting when an unknown error occurs in the handler. Adds the [serialize-error](https://www.npmjs.com/package/serialize-error) library.
=> fix serialization of error messagess from handler

package.json, src/trace/listener.spec.ts, src/trace/listener.ts, yarn.lock
This changes in the PR allow for parsing of the function version from the function arn if there is one. If there is no function version, then a default value of $LATEST is set.
https://datadoghq.atlassian.net/browse/SLS-588
Manually tested using a locally built version of datadog-lambda with the required changes, and making sure the changes make it all the way to the datadog traces.
=> Parse function version from function arn

.github/pull_request_template.md, CONTRIBUTING.md, LICENSE-3rdparty.csv, NOTICE, package.json, scripts/generate_third_party_license_file.py
Replace `datadog-lambda-layer-js` with `datadog-lambda-js`.
Repo is renamed to `datadog-lambda-js`.
=> Rename the repo

package.json
=> Bump major and minor version

package.json, yarn.lock
=> Fix invalid hotshots dependency

src/metrics/kms-service.ts
Correctly decrypt KMS encryption context. 
Addresses issue #116 
Tested manually using KMS symmetric decryption with lambda.
=> Add encryption context to KMS

package.json
Bump version to reflect the latest release
=> bump minor version to 39

package.json
=> Increase version to 3.41.0

CONTRIBUTING.md, README.md, scripts/publish_prod.sh
Updates the repository so the protected HEAD branch is named main
=> master -> main

.github/workflows/build.yml, .github/workflows/check-size.yml, integration_tests/serverless.yml, scripts/build_layers.sh, scripts/check_layer_size.sh, scripts/run_integration_tests.sh
This PR should make the integration testing step faster by using the matrix strategy, it will run tests in parallel.
Increase productivity by reducing waiting time
Codebase was not change but a refactoring for integration testing has been made. This should not break the integration tests and should be fully backward compatible
Current average workflow time for the integration tests step : between 13 and 17 minutes
With this PR, the new time is about 6-7min
=> Add the matrix strategy to workflow to make integration tests faster

.github/.git-hooks/detect-api-keys.py, .github/ISSUE_TEMPLATE/bug_report_template.md, .github/ISSUE_TEMPLATE/feature_request_template.md, .pre-commit-config.yaml, CONTRIBUTING.md, integration_tests/http-requests.js, integration_tests/throw-error-traced.js, scripts/add_new_region.sh, scripts/build_layers.sh, scripts/check_layer_size.sh, scripts/list_layers.sh, scripts/publish_layers.sh, scripts/run_integration_tests.sh, scripts/sign_layers.sh
Adds pre-commit hooks to the repo. Includes a custom hook for detecting Datadog or AWS keys.
Security improvement.
Tested with and without mock keys
=> Add pre-commit hooks

scripts/publish_prod.sh
Changes "commercial AWS GovCloud account" to "production AWS account" in reference to Datadog's prod AWS account.
=> Update verbiage in publish_prod script

scripts/publish_sandbox.sh
Uncomment some lines that were accidentally commented out in a previous PR.
=> Fix publish_sandbox script

integration_tests/snapshots/logs/http-requests_node12.log, integration_tests/snapshots/logs/http-requests_node14.log, integration_tests/snapshots/logs/sync-metrics_node14.log, scripts/publish_sandbox.sh, scripts/run_integration_tests.sh
Stop signing layers published to the sandbox AWS account for testing.
This speeds up the process of releasing a sandbox layer.
=> Do not sign sandbox layers

README.md
Call out the Node.js versions that we officially support like we do for Python.
=> Document supported runtimes

src/metrics/listener.ts
A missing API key is only an issue for this library if the user is sending data synchronously to the backend. If not, the extension or forwarder handles this logic.
Closes https://github.com/DataDog/serverless-plugin-datadog/issues/246
=> feat: Move log line to public metric method

README.md
=> Serverless configurations in one place

.github/workflows/build.yml, .github/workflows/check-size.yml, .github/workflows/codeql-analysis.yml, .github/workflows/update-deps.yml
=> bump github actions

package.json
Fixes https://github.com/DataDog/serverless-plugin-datadog/issues/294
=> feat: Bump ddtrace to 2.14 to fix a stealthy-require bug

.github/workflows/update-snapshots.yml
=> fix the update-snapshots.yml

scripts/publish_layers.sh
Removes commas from arrays in the publish script.
The publish script wasn't running.
=> [hotfix] Remove commas in array in `.sh` file

scripts/publish_sandbox.sh, scripts/run_integration_tests.sh
Update doc to use our new AWS account
=> Use new account in doc

src/trace/span-inferrer.spec.ts, src/trace/span-inferrer.ts
=> feat: Set upstream context for function URLs

integration_tests/snapshots/logs/async-metrics_node12.log, integration_tests/snapshots/logs/async-metrics_node14.log, integration_tests/snapshots/logs/async-metrics_node16.log, integration_tests/snapshots/logs/async-metrics_node18.log, integration_tests/snapshots/logs/esm_node12.log, integration_tests/snapshots/logs/esm_node14.log, integration_tests/snapshots/logs/esm_node16.log, integration_tests/snapshots/logs/esm_node18.log, integration_tests/snapshots/logs/http-requests_node12.log, integration_tests/snapshots/logs/http-requests_node14.log, integration_tests/snapshots/logs/http-requests_node16.log, integration_tests/snapshots/logs/http-requests_node18.log, integration_tests/snapshots/logs/process-input-traced_node12.log, integration_tests/snapshots/logs/process-input-traced_node14.log, integration_tests/snapshots/logs/process-input-traced_node16.log, integration_tests/snapshots/logs/process-input-traced_node18.log, integration_tests/snapshots/logs/status-code-500s_node12.log, integration_tests/snapshots/logs/status-code-500s_node14.log, integration_tests/snapshots/logs/status-code-500s_node16.log, integration_tests/snapshots/logs/status-code-500s_node18.log, integration_tests/snapshots/logs/sync-metrics_node12.log, integration_tests/snapshots/logs/sync-metrics_node14.log, integration_tests/snapshots/logs/sync-metrics_node16.log, integration_tests/snapshots/logs/sync-metrics_node18.log, integration_tests/snapshots/logs/throw-error-traced_node12.log, integration_tests/snapshots/logs/throw-error-traced_node14.log, integration_tests/snapshots/logs/throw-error-traced_node16.log, integration_tests/snapshots/logs/throw-error-traced_node18.log, scripts/run_integration_tests.sh
=> feat: Mask init_start logs

Dockerfile
Add git to Dockerfile to allow installing specific dd-trace version (by git hash)
Prepare for performance testing
CI should pass
=> Add git to prepare performance testing

Dockerfile
Removes native prebuilt libs for taint tracking and the rewriter.
impact to payload size.
=> feat: strip IAST features

Dockerfile, scripts/check_layer_size.sh
=> fix: re-add pprof

yarn.lock
Bumping dependencies with `yarn upgrade`
Good library hygiene, patching upstream security vulnerabilities, etc.
Automated tests should suffice.
=> feat: yarn upgrade

README.md
Adds a note about the Node profiler beta
=> feat: profiler docs

scripts/publish_prod.sh
replace saml2aws with ddsaml2aws
https://datadoghq.atlassian.net/wiki/spaces/ENG/pages/1842709292/US1-Fed+Access#CLI%2FTerraform-Access
=> use ddsaml2aws

scripts/sign_layers.sh
=> feat: Use serverless sandbox bucket

scripts/publish_prod.sh, scripts/publish_sandbox.sh, scripts/run_integration_tests.sh
=> Update aws-vault usage to sso

src/trace/context/extractor.ts, src/trace/context/extractors/step-function.ts
- Fixes invalid type imports introduced in https://github.com/DataDog/datadog-lambda-js/pull/429
Datadog lambda js is throwing a build error:
https://github.com/seek-oss/skuba/actions/runs/6992350107/job/19023877986?pr=1326#step:4:288
Build using tsc/lint locally
=> Fix invalid type imports

integration_tests/serverless.yml, integration_tests/snapshots/logs/process-input-traced_node14.log, integration_tests/snapshots/logs/process-input-traced_node16.log, integration_tests/snapshots/logs/process-input-traced_node18.log, integration_tests/snapshots/logs/process-input-traced_node20.log, integration_tests/snapshots/logs/status-code-500s_node14.log, integration_tests/snapshots/logs/status-code-500s_node16.log, integration_tests/snapshots/logs/status-code-500s_node18.log, integration_tests/snapshots/logs/status-code-500s_node20.log
=> set DD_COLD_START_TRACING to false to fix some flaky integ tests

package.json
=> release: v7.105.0

ci/datasources/regions.yaml, ci/input_files/build.yaml.tpl
Comments out unsupported regions for releases.
Fixes a typo we had on NPM publishing pipeline.
Latest release showcased the issues, it didn't break anything though.
N/A
=> chore: update gitlab pipeline

integration_tests/snapshots/logs/process-input-traced_node16.log, integration_tests/snapshots/logs/process-input-traced_node18.log, integration_tests/snapshots/logs/process-input-traced_node20.log, integration_tests/snapshots/logs/status-code-500s_node16.log, integration_tests/snapshots/logs/status-code-500s_node18.log, integration_tests/snapshots/logs/status-code-500s_node20.log, package.json, yarn.lock
Upgrades ddtrace for @piochelepiotr and friends working on DSM
=> feat: Bump ddtrace to 4.30.0

Dockerfile
We only need arm64 and x86 builds, so we can strip this one
Lightening up the tracer
=> feat: Remove musl build of pprof

ci/datasources/regions.yaml
Deploys our layers to ca-west-1 and il-central-1
Customers want them!
=> feat: Add new regions

ci/input_files/build.yaml.tpl
Automatically retries CI if the runner fails to start. This applies to all stages.
=> feat: retry CI automatically if the runner fails to start

scripts/publish_prod.sh
=> use sso-govcloud-us1-fed-engineering for govcloud

LICENSE-3rdparty.csv, package.json, yarn.lock
Fixes our `LICENSE-3rdparty.csv`.
#525 
n/a
- There should be a license check when `package.json` is updated. Maybe we could leverage `datadog-ci` work on this.
- Didn't add `@types/aws-sdk` since no license could be found – plus it's deprecated.
=> chore: fix licenses

package.json
This PR bumps the layer version to v8.109.0 for the next release.
=> Update version to v8.109.0 for release

package.json, yarn.lock
Bumps ddtrace to 4.37 to support new step functions features 🎉
=> feat: Bump ddtrace to 4.37

ci/input_files/build.yaml.tpl
=> feat: Pin sls at v3

package.json
=> Bump version for release.

package.json
Upgrades the version with a breaking change.
#534
=> breaking: upgrade version with breaking change

README.md
=> update readme for breaking change

package.json, yarn.lock
Upgrades `dd-trace` to `v4.42.0`
Data Streams Monitoring improvements.
=> chore: upgrade `dd-trace` to `v4.42.0`

package.json
Releases `v9.113.0`
New release
=> release: v9.113.0

package.json, yarn.lock
=> feat: update ddtrace

src/trace/patch-console.ts, src/trace/patch-http.ts, yarn.lock
=> feat: bump deps

package.json
Reverts DataDog/datadog-lambda-js#582
=> Revert "v9.116.0"

README.md
https://datadoghq.atlassian.net/browse/DOCS-9796
=> Update `DD_COLD_START_TRACING` env var description

package.json
Bump version 
New release
RCs deployed to self-monitoring: https://gitlab.ddbuild.io/DataDog/datadog-lambda-js/-/pipelines/54624837 
Passing trace propagation tests: https://github.com/DataDog/serverless-self-monitoring/actions/runs/13139176625
=> Bump to v9.119.0

src/trace/context/extractors/sqs.spec.ts, src/trace/context/extractors/sqs.ts
Adds support for extracting Datadog trace context from SQS message attributes when receiving messages from SNS with raw message delivery enabled.
https://github.com/DataDog/datadog-lambda-js/issues/579
Tested manually with `Lambda -> SNS -> SQS -> Lambda` when SNS had raw message delivery enabled:
as you can see, both Lambdas and the SQS inferred span are on the same trace, but there is a missing SNS span (as expected).
Also added unit tests
While we can extract the trace context and create the SQS inferred span, we can't create the SNS inferred span in this scenario since information is lost due to raw message delivery.
=> Extract trace context from SNS->SQS event when SNS has raw message delivery

package.json, yarn.lock
Upgrade version to `10.123.0`
Past incident
Checks
N/A
=> chore: upgrade version to `10.123.0`
